# -*- coding: utf-8 -*-
"""Assign_Cookies.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wEFV9ulPJkN9B1SSkmBzMHH8hhp1l4D
"""

# Leetcode : https://leetcode.com/problems/assign-cookies/

class Solution:
    def findContentChildren(self, g: List[int], s: List[int]) -> int:
        g.sort()
        s.sort()
        content_children=0
        cookie_index=0

        while cookie_index < len(s) and content_children < len(g):
            if s[cookie_index] >= g[content_children]:
                content_children+=1
            cookie_index+=1

        return content_children