# -*- coding: utf-8 -*-
"""Daily Temperatures.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode : https://leetcode.com/problems/daily-temperatures/

class Solution:
    def dailyTemperatures(self, temperatures: List[int]) -> List[int]:
        ans = [0] * len(temperatures)
        stack = []
        for i, temperature in enumerate(temperatures):
          while stack and temperature > temperatures[stack[-1]]:
            index = stack.pop()
            ans[index] = i - index
          stack.append(i)

        return ans