# -*- coding: utf-8 -*-
"""Determine if String Halves Are Alike.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode : https://leetcode.com/problems/determine-if-string-halves-are-alike/

class Solution:
    def halvesAreAlike(self, s: str) -> bool:
        kVowels = 'aeiouAEIOU'
        aVowelsCount = sum(c in kVowels for c in s[:len(s) // 2])
        bVowelsCount = sum(c in kVowels for c in s[len(s) // 2:])
        return aVowelsCount == bVowelsCount