# -*- coding: utf-8 -*-
"""Divide Array Into Arrays With Max Difference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode : https://leetcode.com/problems/divide-array-into-arrays-with-max-difference/

class Solution:
    def divideArray(self, nums: List[int], k: int) -> List[List[int]]:
        ans = []

        nums.sort()

        for i in range(2, len(nums), 3):
          if nums[i] - nums[i - 2] > k:
            return []
          ans.append([nums[i - 2], nums[i - 1], nums[i]])

        return ans