# -*- coding: utf-8 -*-
"""Find First Palindromic String in the Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode :https://leetcode.com/problems/find-first-palindromic-string-in-the-array/
class Solution:
    def firstPalindrome(self, words: List[str]) -> str:
        def isPalindrome(s: str) -> bool:
          i = 0
          j = len(s) - 1
          while i < j:
            if s[i] != s[j]:
              return False
            i += 1
            j -= 1
          return True
        return next((word for word in words if isPalindrome(word)), '')