# -*- coding: utf-8 -*-
"""Find Polygon With the Largest Perimeter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode :https://leetcode.com/problems/find-polygon-with-the-largest-perimeter/
class Solution:
    def largestPerimeter(self, nums: List[int]) -> int:
        prefix = sum(nums)

        for num in sorted(nums, reverse=True):
          prefix -= num
          if prefix > num:
            return prefix + num

        return -1