# -*- coding: utf-8 -*-
"""Minimum_changes_To_Make_Alternating_Binary_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CkmsMT7BlZdM_S1qnkaF8WKkTt57GDl_
"""

#Leetcode :https://leetcode.com/problems/minimum-changes-to-make-alternating-binary-string/

class Solution:
    def minOperations(self, s: str) -> int:
        count=0

        for i in range(len(s)):
            if i%2:
                count+=1 if s[i]=="0" else 0
            else:
                count+=1 if s[i]=="1" else 0
        return min(count,len(s)-count)