# -*- coding: utf-8 -*-
"""Minimum Length of String After Deleting Similar Ends.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode :https://leetcode.com/problems/minimum-length-of-string-after-deleting-similar-ends/
class Solution:
    def minimumLength(self, s: str) -> int:
        i = 0
        j = len(s) - 1

        while i < j and s[i] == s[j]:
          c = s[i]
          while i <= j and s[i] == c:
            i += 1
          while i <= j and s[j] == c:
            j -= 1

        return j - i + 1