# -*- coding: utf-8 -*-
"""Minimum Number of Operations to Make Array Empty.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18E5k79vqeTulP7XO6q9x73OChTcfQSEE
"""

# Leetcode : https://leetcode.com/problems/minimum-number-of-operations-to-make-array-empty/

class Solution:
    def minOperations(self, nums: List[int]) -> int:
        count=Counter(nums)
        res=0
        for n,c in count.items():
            if c==1:
                return -1

            res+=math.ceil(c/3)
        return res