# -*- coding: utf-8 -*-
"""Number of Laser Beams in a Bank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18E5k79vqeTulP7XO6q9x73OChTcfQSEE
"""

# Leetcode : https://leetcode.com/problems/number-of-laser-beams-in-a-bank/

class Solution:
    def numberOfBeams(self, bank: List[str]) -> int:
        prev= bank[0].count("1")
        res=0

        for i in range(1,len(bank)):
            curr = bank[i].count("1")
            if curr:
                res += (prev * curr)
                prev=curr

        return res