# -*- coding: utf-8 -*-
"""Number_of_Dice_Rolls_With_Target_Sum.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-AxXO6IwP6NPAItiFGL7XqXDpTKjlyz
"""

#Leetcode : https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/

class Solution:
    def numRollsToTarget(self, n: int, k: int, target: int) -> int:
        MOD= 10**9 + 7

        cache={}

        def count(n,target):
            if n==0:
                return 1 if target ==0 else 0

            if (n,target) in cache:
                return cache[(n,target)]

            res=0
            for val in range(1,k+1):
                res=(res+count(n-1,target-val))%MOD
            cache[(n,target)] =res

            return res

        return count(n,target)