# -*- coding: utf-8 -*-
"""Remove Nth Node From End of List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode :https://leetcode.com/problems/remove-nth-node-from-end-of-list/
class Solution:
    def removeNthFromEnd(self, head: Optional[ListNode], n: int) -> Optional[ListNode]:
        slow = head
        fast = head

        for _ in range(n):
          fast = fast.next
        if not fast:
          return head.next

        while fast.next:
          slow = slow.next
          fast = fast.next
        slow.next = slow.next.next

        return head