# -*- coding: utf-8 -*-
"""Set Mismatch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode : https://leetcode.com/problems/set-mismatch/

class Solution:
    def findErrorNums(self, nums: List[int]) -> List[int]:
        for num in nums:
          if nums[abs(num) - 1] < 0:
            duplicate = abs(num)
          else:
            nums[abs(num) - 1] *= -1

        for i, num in enumerate(nums):
          if num > 0:
            return [duplicate, i + 1]