# -*- coding: utf-8 -*-
"""Unique Number of Occurrences.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JhVeoGM25AbjjauGKpXEmOw6RZwZ-MxG
"""

# Leetcode : https://leetcode.com/problems/unique-number-of-occurrences/

class Solution:
    def uniqueOccurrences(self, arr: List[int]) -> bool:
        count = collections.Counter(arr)
        occurrences = set()

        for value in count.values():
          if value in occurrences:
            return False
          occurrences.add(value)

        return True